const gridData = [
	{
		bgColor: "bg-tulip-tree-400",
		widthProject: "w-44",
		heightProject: "h-24 p-3",
		containerText: "Bio",
		textPropeties: "text-7xl text-cod-gray-100",
		columnProperties: " h-52",
		flexItem: "flex items-end",
	},
	{ isEmpty: true },
	{ isEmpty: true },
	{ isEmpty: true },
	{
		bgColor: "bg-valencia-500",
		widthProject: "w-full",
		heightProject: "h-32 p-5",
		containerText: "Todone App",
		textPropeties: "text-5xl text-cod-gray-100 ",
		columnProperties: "col-span-2 h-72",
		flexItem: "flex items-end",
	},
	{ isEmpty: true },
	{ isEmpty: true },
	{ isEmpty: true },
	{
		bgColor: "bg-abbey-700",
		widthProject: "w-2/3",
		heightProject: "h-32 p-5",
		containerText: "MVC Blog",
		textPropeties: "text-7xl text-cod-gray-100 ",
		columnProperties: "col-span-2 h-72",
		flexItem: "flex items-end",
	},
	{
		bgColor: "bg-valencia-400",
		widthProject: "w-2/3",
		heightProject: "h-24 p-5",
		containerText: "Mongo Blog DataBase",
		textPropeties: "text-3xl text-cod-gray-100 ",
		columnProperties: " h-72 justify-end ",
		flexItem: "flex items-end",
	},
	{ isEmpty: true },
	{ isEmpty: true },
	{ isEmpty: true },
	{
		widthProject: "w-2/3",
		heightProject: "h-24 p-5",
		columnProperties: "col-span-2 justify-center h-72",
		textPropeties: "text-lg text-abbey-700 text-start",
		containerText:
			"I'm a Full-Stack developer with a background in art, design and game development. I excel in crafting mobile-first applications with smooth designs and intuitive usability. I'm passionate about problem-solving and debugging, and I pride myself on delivering exceptional results.",
		flexItem: "flex items-end",
	},
	{
		bgColor: "bg-tulip-tree-400",
		widthProject: "w-5/12",
		heightProject: "h-full p-5",
		containerText: "Skills",
		textPropeties: "text-3xl text-cod-gray-100  text-center",
		columnProperties: " h-full justify-end row-span-2",
		flexItem: "flex-wrap items-start",
		skillsBody: [
			"MERN Stack",
			"Webpack",
			"MongoDB",
			"Redux",
			"Jest",
			"React",
			"Express.js",
			"OOP",
			"Tailwind CSS",
			"Bootstrap",
			"SQL",
			"CSS",
			"HTML5",
			"REST APIs",
			"Vite",
			"JWT",
			"MVC",
			"ORM",
			"Mongoose",
			"Sequelize",
		],
	},
	{
		bgColor: "bg-valencia-400",
		widthProject: "w-2/3",
		heightProject: "h-28 p-5",
		languagesBody: ["English", "Spanish", "Czech"],
		textPropeties: "text-3xl text-cod-gray-100 ",
		columnProperties: "h-32 justify-start ",
		flexItem: "flex items-end",
	},
];

export default gridData;
