const gridData = [
	{
		bgColor: "bg-tulip-tree-300 hover:bg-tulip-tree-400",
		widthProject: "w-3/4 md:w-44",
		heightProject: "h-24 p-3",
		containerText: "About Me",
		textPropeties: "text-3xl md:text-5xl text-cod-gray-100",
		columnProperties: "h-52 cursor-pointer",
		flexItem: "flex items-end",
		idTag: "AboutMeBtn",
		containerId: "AboutMeContainer",
		scroll: true,
	},
	{ isEmpty: true },
	{ isEmpty: true },
	{ isEmpty: true },

	{
		bgColor: "bg-valencia-500 hover:bg-valencia-600",
		widthProject: "w-5/6 md:w-full",
		heightProject: "h-auto p-5",
		containerText: "Interactive Portfolio",
		textPropeties: "text-3xl md:text-5xl text-cod-gray-100",
		columnProperties: "col-span-1 md:col-span-2 h-auto md:h-72 justify-end md:justify-start",
		flexItem: "flex-wrap items-end",
		idTag: "PortfolioBtn",
		link: `https://amendezstudio.com`,
		containerId: "PortfolioContainer",
		listbody: ["React", "GSAP", "TypeScript", "Three.js", "Cloudflare", "Vite"],
		listStyles: "text-cod-gray-100 text-sm opacity-0",
		listId: "PortfolioList",
		target: "_blank",
	},
	{ isEmpty: true },
	{ isEmpty: true },
	{ isEmpty: true },
	{
		bgColor: "bg-abbey-700 hover:bg-abbey-800",
		widthProject: "w-4/5 md:w-2/3 lg:w-2/3",
		heightProject: "h-auto p-5",
		containerText: "MVC Blog",
		textPropeties: "text-4xl md:text-6xl lg:text-7xl text-cod-gray-100",
		columnProperties: "col-span-1 md:col-span-2 md:row-span-2 h-auto flex-wrap items-end",
		flexItem: "flex-wrap items-end",
		idTag: "MVCBtn",
		link: `https://mvc-practice.onrender.com/login`,
		containerId: "MVCContainer",
		listStyles: "text-cod-gray-100 text-sm opacity-0",
		listbody: [
			"Javascript",
			"Node.js",
			"MVC",
			"ORM Sequelize",
			"SQL",
			"Handlebars view engine",
			"Tailwind CSS",
			"PostCSS",
			"Express.js",
			"Mysql",
			"Cloud Service Heroku",
		],
		listId: "MVCList",
		target: "_blank",
	},

	{
		bgColor: "bg-valencia-300 hover:bg-valencia-400",
		widthProject: "w-4/5 md:w-2/3 lg:w-2/3",
		heightProject: "h-auto p-5",
		containerText: "Mongo Blog DataBase",
		textPropeties: "text-2xl lg:text-3xl text-abbey-700",
		columnProperties: "h-auto md:h-72 justify-end",
		flexItem: "flex-wrap items-end",
		idTag: "MongoBtn",
		link: `https://github.com/Andatax/social-network-mdb`,
		listStyles: "text-abbey-700 text-sm opacity-0",
		listbody: ["Javascript", "Node.js", "ORM Mongoose", "MongoDb", "Express.js", "Insomnia"],
		listId: "MongoList",
		target: "_blank",
	},
	{ isEmpty: true },
	{ isEmpty: true },
	{ isEmpty: true },
	{
		bgColor: "bg-tulip-tree-700 hover:bg-tulip-tree-900",
		widthProject: "w-5/6 md:w-3/4 lg:w-3/4",
		heightProject: "h-auto p-5",
		containerText: "Capiii",
		textPropeties: "text-3xl md:text-5xl text-cod-gray-100",
		columnProperties: "h-auto md:h-72 justify-end mt-8 md:mt-12",
		flexItem: "flex-wrap items-end",
		idTag: "CapiiiBtn",
		link: `https://github.com/zaort/capiii`,
		containerId: "TodoneContainer",
		listbody: [
			"Javascript",
			"Node.js",
			"Jest",
			"MERN",
			"NoSql",
			"React",
			"Tailwind CSS",
			"Redux",
			"GraphQL",
		],
		listStyles: "text-cod-gray-100 text-sm opacity-0",
		listId: "Capiii",
		target: "_blank",
	},
	{ isEmpty: true },
	{ isEmpty: true },
	{ isEmpty: true },
	{
		widthProject: "w-full",
		heightProject: "h-auto p-5",
		columnProperties: "md:col-span-3 justify-center h-auto md:h-72 flex items-start pointer-events-none",
		textPropeties: "text-sm lg:text-lg text-abbey-700 text-start",
		containerText:
			"I'm a Full-Stack developer with a background in art, design and game development. I excel in crafting mobile-first applications with smooth designs and intuitive usability. I'm passionate about problem-solving and debugging, and I pride myself on delivering exceptional results.",
		flexItem: "flex items-start",
		idTag: "AboutMeBody",
		link: "",
	},
	{
		bgColor: "bg-tulip-tree-300 hover:bg-tulip-tree-400",
		widthProject: "w-3/5 md:w-5/12 lg:w-5/12",
		heightProject: "h-full p-5",
		containerText: "Skills",
		textPropeties: "text-sm md:text-xl lg:text-3xl text-abbey-700 text-center",
		columnProperties: "h-full justify-start md:row-span-2 items-start",
		flexItem: "flex-wrap items-start",
		listStyles: "text-abbey-700 text-sm opacity-0",
		listbody: [
			"MERN Stack",
			"Webpack",
			"MongoDB",
			"Redux",
			"Jest",
			"React",
			"Express.js",
			"OOP",
			"Tailwind CSS",
			"Bootstrap",
			"SQL",
			"CSS",
			"HTML5",
			"REST APIs",
			"Vite",
			"JWT",
			"MVC",
			"ORM",
			"Mongoose",
			"Sequelize",
			"Node.js",
			"GSAP",
		],
		idTag: "Skills",
		listId: "SkillsList",
	},
	{ isEmpty: true },
	{ isEmpty: true },
	{ isEmpty: true },

	{
		bgColor: "bg-valencia-600",
		widthProject: "w-3/5 md:w-2/3",
		heightProject: "h-auto md:h-60 p-5",
		listbody: ["English", "Spanish", "Czech"],
		textPropeties: "text-lg md:text-3xl lg:text-9xl text-cod-gray-100",
		columnProperties: "h-auto md:h-32 justify-end",
		flexItem: "flex items-end",
		listStyles: "text-cod-gray-100 text-sm md:text-xl lg:text-3xl",
		idTag: "Languages",
	},
];

export default gridData;
